import {
  GraduationCap,
  Home,
  BookOpen,
  BarChart3,
  LogOut,
  Menu,
  X,
  MessageSquare,
  Award,
  User,
  Tags,
  Users,
  FileText,
  ClipboardList,
  Settings,
} from 'lucide-react';

export const Icons = {
  Dashboard: Home,
  Courses: BookOpen,
  MyEnrollments: BarChart3,
  Certificates: Award,
  Chat: MessageSquare,
  Profile: User,
  LogOut,
  Menu,
  Logo: GraduationCap,
  Close: X,
  Categories: Tags,
  Students: Users,
  Assignments: FileText,
  Quizzes: ClipboardList,
  Analytics: BarChart3,
  Settings: Settings,
};
